name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.3'

      - name: Run tests
        run: go test -v ./...

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: joshwatley/go-tunol:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/go-tunol
            mkdir -p /opt/go-tunol/data
            docker pull joshwatley/go-tunol:latest
            docker stop go-tunol || true
            docker rm go-tunol || true
            docker run -d \
              --name go-tunol \
              --restart unless-stopped \
              -p 8001:8001 \
              -v /opt/go-tunol/data:/opt/go-tunol/data \
              -e SERVER_URL=${{ secrets.SERVER_URL }} \
              -e SERVER_PORT=${{ secrets.SERVER_PORT }} \
              -e GITHUB_CLIENT_ID=${{ secrets.GH_CLIENT_ID }} \
              -e GITHUB_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }} \
              -e DB_PATH=${{ secrets.DB_PATH }} \
              -e LOG_LEVEL=${{ vars.LOG_LEVEL }} \
              -e USE_SUBDOMAINS=${{ vars.USE_SUBDOMAINS }} \
              joshwatley/go-tunol:latest
